//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaYonetimSistemi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aidatlar
    {
        public int Id { get; set; }
        public decimal AidatTutari { get; set; }
        public int AidatGunu { get; set; }
        public int SiteBinaId { get; set; }
        public Nullable<bool> AidatlarGonderildi { get; set; }
    
        public virtual SiteBina SiteBina { get; set; }
    }
}
