//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaYonetimSistemi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        public int Id { get; set; }
        public int SiteBina { get; set; }
        public string DuyuruBasligi { get; set; }
        public string DuyuruAciklamasi { get; set; }
        public string DuyuruTarihi { get; set; }
        public string DuyuruBitisTarihi { get; set; }
    
        public virtual SiteBina SiteBina1 { get; set; }
    }
}
